# Script para eliminar emojis de todos los archivos TSX del proyecto Governex
# Ejecutar desde d:\Governex

$files = Get-ChildItem -Path "d:\Governex\src" -Recurse -Include "*.tsx","*.ts" | Where-Object { $_.FullName -notmatch "node_modules" }

# Tabla de reemplazos: emoji -> texto neutro o vacío
$replacements = @(
    # Botones de acción con texto
    @{ From = '✨ Generar con IA'; To = 'Generar con IA' },
    @{ From = '✨ Regenerar con IA'; To = 'Regenerar con IA' },
    @{ From = '✨ IA'; To = 'IA' },
    @{ From = '✨ {aiGenerated'; To = '{aiGenerated' },
    @{ From = "✨ {tieneItems ? 'Regenerar matriz con Governex IA' : 'Generar matriz con Governex IA'}"; To = "{tieneItems ? 'Regenerar matriz con Governex IA' : 'Generar matriz con Governex IA'}" },
    @{ From = '✨ Generar matriz con IA'; To = 'Generar matriz con IA' },
    @{ From = "✨ {isGenerating"; To = "{isGenerating" },
    @{ From = '✨ Generar'; To = 'Generar' },
    @{ From = '✨'; To = '' },
    @{ From = '⏳ Generando...'; To = 'Generando...' },
    @{ From = '⏳'; To = '' },
    @{ From = '💾 Guardar Cambios'; To = 'Guardar Cambios' },
    @{ From = '💾 Guardar ficha'; To = 'Guardar ficha' },
    @{ From = '💾 Guardar'; To = 'Guardar' },
    @{ From = '💾'; To = '' },
    @{ From = '✏️ Editar / Agregar'; To = 'Editar / Agregar' },
    @{ From = '✏️ Editar'; To = 'Editar' },
    @{ From = "✏️ {aiGenerated ? 'Regenerar con IA' : 'Generar con IA'}"; To = "{aiGenerated ? 'Regenerar con IA' : 'Generar con IA'}" },
    @{ From = '✏️'; To = '' },
    @{ From = '🗑️'; To = '' },
    @{ From = '➕ Nuevo'; To = 'Nuevo' },
    @{ From = '➕'; To = '' },
    @{ From = '🔗'; To = '' },
    @{ From = '❌ '; To = '' },
    @{ From = '❌'; To = '' },
    @{ From = '✅ '; To = '' },
    @{ From = '✅'; To = '' },
    @{ From = '⚠️'; To = '' },
    @{ From = '✕'; To = '×' },
    # Títulos de página con emoji
    @{ From = '⚙️ Diseño y Desarrollo'; To = 'Diseño y Desarrollo' },
    @{ From = '⚙️ Requerimientos para Productos y Servicios'; To = 'Requerimientos para Productos y Servicios' },
    @{ From = '⚙️'; To = '' },
    @{ From = '🚨 No Conformidades'; To = 'No Conformidades' },
    @{ From = '🚨 Nueva No Conformidad'; To = 'Nueva No Conformidad' },
    @{ From = '🚨'; To = '' },
    @{ From = '🛠️ Acciones Correctivas'; To = 'Acciones Correctivas' },
    @{ From = '🛠️ Nueva Acción Correctiva'; To = 'Nueva Acción Correctiva' },
    @{ From = '🛠️'; To = '' },
    @{ From = '📌'; To = '' },
    @{ From = '📂 '; To = '' },
    @{ From = '📂'; To = '' },
    @{ From = '📚 Cursos / Grados'; To = 'Cursos / Grados' },
    @{ From = '📚 Cursos'; To = 'Cursos' },
    @{ From = '📚'; To = '' },
    @{ From = '📖 '; To = '' },
    @{ From = '📖'; To = '' },
    @{ From = '🗂️ '; To = '' },
    @{ From = '🗂️'; To = '' },
    @{ From = '🎓 Institución Educativa'; To = 'Institución Educativa' },
    @{ From = '🎓 Ficha Técnica'; To = 'Ficha Técnica' },
    @{ From = '🎓'; To = '' },
    @{ From = '📋 Ficha Técnica'; To = 'Ficha Técnica' },
    @{ From = '📋 Fichas Técnicas'; To = 'Fichas Técnicas' },
    @{ From = '📋'; To = '' },
    @{ From = '📊 Vista Matriz'; To = 'Vista Matriz' },
    @{ From = '📊 '; To = '' },
    @{ From = '📊'; To = '' },
    @{ From = '📝'; To = '' },
    @{ From = '💡 '; To = '' },
    @{ From = '💡'; To = '' },
    @{ From = '🎯 Objetivo:'; To = 'Objetivo:' },
    @{ From = '🎯'; To = '' },
    @{ From = '💼 Control de Ventas'; To = 'Control de Ventas' },
    @{ From = '💼'; To = '' },
    @{ From = '👁️ Ver Ficha Técnica'; To = 'Ver Ficha Técnica' },
    @{ From = '👁️'; To = '' },
    @{ From = '🔬'; To = '' },
    @{ From = '🔋'; To = '' },
    @{ From = '⚓'; To = '' },
    @{ From = '🤝'; To = '' },
    @{ From = '🗺️'; To = '' },
    @{ From = '🔄'; To = '' },
    @{ From = '🧭'; To = '' },
    @{ From = '♾️'; To = '' },
    @{ From = '👤'; To = '' },
    @{ From = '🤖'; To = '' },
    @{ From = '💬'; To = '' },
    @{ From = '🔒'; To = '' },
    @{ From = '🛡️'; To = '' },
    @{ From = '🔑'; To = '' },
    @{ From = '📧'; To = '' },
    @{ From = '🏢'; To = '' },
    @{ From = '🏭'; To = '' },
    @{ From = '🏗️'; To = '' },
    @{ From = '🌐'; To = '' },
    @{ From = '📈'; To = '' },
    @{ From = '📉'; To = '' },
    @{ From = '📆'; To = '' },
    @{ From = '📅'; To = '' },
    @{ From = '📁'; To = '' },
    @{ From = '🗓️'; To = '' },
    @{ From = '🔍'; To = '' },
    @{ From = '🔎'; To = '' },
    @{ From = '💰'; To = '' },
    @{ From = '🧩'; To = '' },
    @{ From = '🧪'; To = '' },
    @{ From = '🧬'; To = '' },
    @{ From = '🧠'; To = '' },
    @{ From = '💊'; To = '' },
    @{ From = '🌿'; To = '' },
    @{ From = '🌱'; To = '' },
    @{ From = '🔧'; To = '' },
    @{ From = '🔨'; To = '' },
    @{ From = '⛏️'; To = '' },
    @{ From = '🏆'; To = '' },
    @{ From = '🥇'; To = '' },
    @{ From = '🎖️'; To = '' },
    @{ From = '🎪'; To = '' },
    @{ From = '🎨'; To = '' },
    @{ From = '🎭'; To = '' },
    @{ From = '🎬'; To = '' },
    @{ From = '📷'; To = '' },
    @{ From = '📸'; To = '' },
    @{ From = '🖼️'; To = '' },
    @{ From = '🗒️'; To = '' },
    @{ From = '📑'; To = '' },
    @{ From = '📃'; To = '' },
    @{ From = '📄'; To = '' },
    @{ From = '🔐'; To = '' },
    @{ From = '🔓'; To = '' },
    @{ From = '🔏'; To = '' },
    @{ From = '🔺'; To = '' },
    @{ From = '🔻'; To = '' },
    @{ From = '⭐'; To = '' },
    @{ From = '🌟'; To = '' },
    @{ From = '💫'; To = '' },
    @{ From = '✔️'; To = '' },
    @{ From = '☑️'; To = '' },
    @{ From = '🔵'; To = '' },
    @{ From = '🟢'; To = '' },
    @{ From = '🟡'; To = '' },
    @{ From = '🔴'; To = '' },
    @{ From = '⚡'; To = '' },
    @{ From = '🚀'; To = '' },
    @{ From = '🛸'; To = '' },
    @{ From = '💎'; To = '' },
    @{ From = '🏅'; To = '' },
    @{ From = '🎯'; To = '' },
    @{ From = '📍'; To = '' },
    @{ From = '📎'; To = '' },
    @{ From = '🖇️'; To = '' },
    @{ From = '🖊️'; To = '' },
    @{ From = '✒️'; To = '' },
    @{ From = '🖋️'; To = '' },
    @{ From = '📐'; To = '' },
    @{ From = '📏'; To = '' },
    @{ From = '📌'; To = '' },
    @{ From = '🔖'; To = '' },
    @{ From = '🏷️'; To = '' },
    @{ From = '💡'; To = '' },
    @{ From = '🔆'; To = '' },
    @{ From = '🔅'; To = '' },
    @{ From = '🔔'; To = '' },
    @{ From = '🔕'; To = '' },
    @{ From = '🔇'; To = '' },
    @{ From = '🔈'; To = '' },
    @{ From = '🔉'; To = '' },
    @{ From = '🔊'; To = '' },
    @{ From = '📣'; To = '' },
    @{ From = '📢'; To = '' },
    @{ From = '🔀'; To = '' },
    @{ From = '🔁'; To = '' },
    @{ From = '🔂'; To = '' },
    @{ From = '▶️'; To = '' },
    @{ From = '⏸️'; To = '' },
    @{ From = '⏹️'; To = '' },
    @{ From = '⏺️'; To = '' },
    @{ From = '⏭️'; To = '' },
    @{ From = '⏮️'; To = '' },
    @{ From = '⏩'; To = '' },
    @{ From = '⏪'; To = '' },
    @{ From = '⬆️'; To = '' },
    @{ From = '⬇️'; To = '' },
    @{ From = '⬅️'; To = '' },
    @{ From = '➡️'; To = '' },
    @{ From = '↩️'; To = '' },
    @{ From = '↪️'; To = '' },
    @{ From = '🔙'; To = '' },
    @{ From = '🔚'; To = '' },
    @{ From = '🔛'; To = '' },
    @{ From = '🔜'; To = '' },
    @{ From = '🔝'; To = '' },
    @{ From = '🆕'; To = '' },
    @{ From = '🆗'; To = '' },
    @{ From = '🆙'; To = '' },
    @{ From = '🆒'; To = '' },
    @{ From = '🆓'; To = '' },
    @{ From = '🆘'; To = '' },
    @{ From = '🆚'; To = '' },
    @{ From = '🆖'; To = '' },
    @{ From = '❗'; To = '' },
    @{ From = '❕'; To = '' },
    @{ From = '❓'; To = '' },
    @{ From = '❔'; To = '' },
    @{ From = '‼️'; To = '' },
    @{ From = '⁉️'; To = '' },
    @{ From = '🔃'; To = '' },
    @{ From = '🔄'; To = '' },
    @{ From = '➰'; To = '' },
    @{ From = '➿'; To = '' },
    @{ From = '〽️'; To = '' },
    @{ From = '✳️'; To = '' },
    @{ From = '✴️'; To = '' },
    @{ From = '❇️'; To = '' },
    @{ From = '©️'; To = '' },
    @{ From = '®️'; To = '' },
    @{ From = '™️'; To = '' },
    @{ From = '🎗️'; To = '' },
    @{ From = '🎟️'; To = '' },
    @{ From = '🎫'; To = '' },
    @{ From = '😊'; To = '' },
    @{ From = '😀'; To = '' },
    @{ From = '😁'; To = '' },
    @{ From = '😂'; To = '' },
    @{ From = '🤣'; To = '' },
    @{ From = '😃'; To = '' },
    @{ From = '😄'; To = '' },
    @{ From = '😅'; To = '' },
    @{ From = '😆'; To = '' },
    @{ From = '😉'; To = '' },
    @{ From = '😋'; To = '' },
    @{ From = '😎'; To = '' },
    @{ From = '😍'; To = '' },
    @{ From = '🥰'; To = '' },
    @{ From = '🤩'; To = '' }
)

$totalFiles = 0
$totalChanges = 0

foreach ($file in $files) {
    $content = [System.IO.File]::ReadAllText($file.FullName, [System.Text.Encoding]::UTF8)
    $original = $content
    
    foreach ($r in $replacements) {
        $content = $content.Replace($r.From, $r.To)
    }
    
    # Regex amplio para capturar emojis que no entraron en la tabla
    # Rango Unicode de emojis
    $emojiPattern = '[^\u0000-\u024F\u1E00-\u1EFF\u2010-\u2027\u2030-\u205E\u2060-\u206F\u2100-\u218F\u2190-\u21FF\u2200-\u27BF\u2900-\u2BFF\u3000-\u303F\uFB00-\uFFFD]'
    # Eliminar emojis restantes usando regex
    $content = [regex]::Replace($content, $emojiPattern, '')
    
    if ($content -ne $original) {
        [System.IO.File]::WriteAllText($file.FullName, $content, [System.Text.Encoding]::UTF8)
        $totalFiles++
        Write-Host "✓ Limpiado: $($file.Name)"
    }
}

Write-Host ""
Write-Host "Proceso completado: $totalFiles archivos modificados"
